runtime: nodejs18
instance_class: F2
env_variables:
  MONGODB_URI: "mongodb+srv://aakashmahadik2310:0glAjLcwwvYVEJxq@cluster0.zc70kvw.mongodb.net/?retryWrites=true&w=majority"
handlers:
  - url: /api/.*
    script: app.js



